// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvfNCZLmlyUK3O_Wh06S8vNuoZc1snpcA',
    appId: '1:11806084841:web:597e814998b8cf89ee6a78',
    messagingSenderId: '11806084841',
    projectId: 'do-thi-thong-minh',
    authDomain: 'do-thi-thong-minh.firebaseapp.com',
    storageBucket: 'do-thi-thong-minh.appspot.com',
    measurementId: 'G-JHV4Q8TPDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSnWlx93KOEKhoVW2CjBw38G4KejpV7Pg',
    appId: '1:11806084841:android:4b38aa28f4ea3138ee6a78',
    messagingSenderId: '11806084841',
    projectId: 'do-thi-thong-minh',
    storageBucket: 'do-thi-thong-minh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcAU50YMls-AUIKEDpJ4GDrNIFkZk7i6Q',
    appId: '1:11806084841:ios:f5025ab570a1d968ee6a78',
    messagingSenderId: '11806084841',
    projectId: 'do-thi-thong-minh',
    storageBucket: 'do-thi-thong-minh.appspot.com',
    iosBundleId: 'n.quang.dttm.doThiThongMinh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcAU50YMls-AUIKEDpJ4GDrNIFkZk7i6Q',
    appId: '1:11806084841:ios:ee4283c081baeeb6ee6a78',
    messagingSenderId: '11806084841',
    projectId: 'do-thi-thong-minh',
    storageBucket: 'do-thi-thong-minh.appspot.com',
    iosBundleId: 'n.quang.dttm.doThiThongMinh.RunnerTests',
  );
}
